name: 👍Acceso a la Fortaleza Prohibida

on:
  workflow_dispatch:

jobs:
  acceso-a-la-base:
    runs-on: ubuntu-latest
    steps:
      - name: El agente llega a la Fortaleza
        run: |
          echo "Agente ${{ github.actor }} ha llegado a la Fortaleza Prohibida"
          echo ""
          echo "Buscar archivos de la Legión🗂️"
          ls -la
          echo ""
          echo "☢️pero que pasó aquí? No hay nada"

      - name: "🃏Guason desbloquea la boveda"
        uses: actions/checkout@v4

      - name: "🔑Ahora sí, vamos a Explorar la boveda"
        run: |
          echo "Explorando la boveda de la Fortaleza Prohibida"
          ls -la
          echo "✅ Funciona"
          echo "🔐 La boveda ha sido explorada"
          echo ""
          echo "🗺️Planes:"
          echo ""
          ls planes/
          echo ""
          echo "🃏Villanos:"
          ls miembros/
          echo ""
          echo "🕵️Inteligencia:"
          ls inteligencia/
          echo ""
          echo "📜Documentos:"
          ls docs/
          echo ""
          # echo "🤫Archivos secretos:"
          # ls secretos/ 2>/dev/null || echo "⚠️ La carpeta secretos/ no existe"
          echo "🔚Fin de la exploración de la boveda🔚"
