name: 📣Comunicador de la Legión

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Qué villano envia el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Joker
          - Thanos
          - Green Goblin
      mensaje:
        description: "Contenido del mensaje"
        required: true
        default: "La misión fué un éxito"

      prioridad:
        description: "Nivel de Prioridad"
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🟡 Alta
          - 🔴 Crítica
jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir inputs
        run: |
          echo "Iniciando la transmisión del mensaje..."
          echo "Villano: ${{ inputs.villano }}"
          echo "Mensaje: ${{ inputs.mensaje }}"
          echo "Prioridad: ${{ inputs.prioridad }}"
